- name: Set Pacifica User Facts
  set_fact:
    pacifica_user_name: "{{ __pacifica_user_name }}"
  when: pacifica_user_name is not defined

- name: Set Pacifica Group Facts
  set_fact:
    pacifica_group_name: "{{ __pacifica_group_name }}"
  when: pacifica_group_name is not defined

- name: Add pacifica group
  ansible.builtin.group:
    name: "{{ pacifica_group_name }}"
    state: present
    system: yes

- name: Add pacifica user
  ansible.builtin.user:
    name: "{{ pacifica_user_name }}"
    comment: Pacifica Local NonPriv User
    group: "{{ pacifica_group_name }}"
    state: present
    system: yes
