---
- name: Add pacifica group
  ansible.builtin.group:
    name: "{{ pacifica_group_name }}"
    state: present
    system: true
- name: Add pacifica user
  ansible.builtin.user:
    name: "{{ pacifica_user_name }}"
    comment: Pacifica Local NonPriv User
    group: "{{ pacifica_group_name }}"
    state: present
    system: true
  when: pacifica_user_name != 'root'
